/* 筋メシ - プリセットデータ */
'use strict';

const MUSCLES = {
  chest:     { label: '胸',     order: 1 },
  back:      { label: '背中',   order: 2 },
  legs:      { label: '脚',     order: 3 },
  shoulders: { label: '肩',     order: 4 },
  arms:      { label: '腕',     order: 5 },
  core:      { label: '腹・体幹', order: 6 },
  cardio:    { label: '有酸素', order: 7 },
};

/* unit: 'kg' = 重量×回数, 'bw' = 自重(回数のみ), 'min' = 分 */
const PRESET_EXERCISES = [
  { id: 'px01', name: 'ベンチプレス',            muscle: 'chest',     unit: 'kg' },
  { id: 'px02', name: 'ダンベルプレス',          muscle: 'chest',     unit: 'kg' },
  { id: 'px03', name: 'インクラインベンチプレス', muscle: 'chest',     unit: 'kg' },
  { id: 'px04', name: 'チェストプレス',          muscle: 'chest',     unit: 'kg' },
  { id: 'px05', name: 'ダンベルフライ',          muscle: 'chest',     unit: 'kg' },
  { id: 'px06', name: 'ケーブルクロスオーバー',  muscle: 'chest',     unit: 'kg' },
  { id: 'px07', name: '腕立て伏せ',              muscle: 'chest',     unit: 'bw' },
  { id: 'px08', name: 'ディップス',              muscle: 'chest',     unit: 'bw' },
  { id: 'px10', name: 'デッドリフト',            muscle: 'back',      unit: 'kg' },
  { id: 'px11', name: '懸垂（チンニング）',      muscle: 'back',      unit: 'bw' },
  { id: 'px12', name: 'ラットプルダウン',        muscle: 'back',      unit: 'kg' },
  { id: 'px13', name: 'ベントオーバーロー',      muscle: 'back',      unit: 'kg' },
  { id: 'px14', name: 'シーテッドロー',          muscle: 'back',      unit: 'kg' },
  { id: 'px15', name: 'ワンハンドロー',          muscle: 'back',      unit: 'kg' },
  { id: 'px20', name: 'スクワット',              muscle: 'legs',      unit: 'kg' },
  { id: 'px21', name: 'レッグプレス',            muscle: 'legs',      unit: 'kg' },
  { id: 'px22', name: 'ブルガリアンスクワット',  muscle: 'legs',      unit: 'kg' },
  { id: 'px23', name: 'ランジ',                  muscle: 'legs',      unit: 'kg' },
  { id: 'px24', name: 'レッグエクステンション',  muscle: 'legs',      unit: 'kg' },
  { id: 'px25', name: 'レッグカール',            muscle: 'legs',      unit: 'kg' },
  { id: 'px26', name: 'カーフレイズ',            muscle: 'legs',      unit: 'kg' },
  { id: 'px27', name: 'ヒップスラスト',          muscle: 'legs',      unit: 'kg' },
  { id: 'px30', name: 'ショルダープレス',        muscle: 'shoulders', unit: 'kg' },
  { id: 'px31', name: 'サイドレイズ',            muscle: 'shoulders', unit: 'kg' },
  { id: 'px32', name: 'リアレイズ',              muscle: 'shoulders', unit: 'kg' },
  { id: 'px33', name: 'フロントレイズ',          muscle: 'shoulders', unit: 'kg' },
  { id: 'px34', name: 'アップライトロー',        muscle: 'shoulders', unit: 'kg' },
  { id: 'px40', name: 'バーベルカール',          muscle: 'arms',      unit: 'kg' },
  { id: 'px41', name: 'ダンベルカール',          muscle: 'arms',      unit: 'kg' },
  { id: 'px42', name: 'ハンマーカール',          muscle: 'arms',      unit: 'kg' },
  { id: 'px43', name: 'トライセプスエクステンション', muscle: 'arms', unit: 'kg' },
  { id: 'px44', name: 'ケーブルプレスダウン',    muscle: 'arms',      unit: 'kg' },
  { id: 'px45', name: 'ナローベンチプレス',      muscle: 'arms',      unit: 'kg' },
  { id: 'px50', name: 'プランク',                muscle: 'core',      unit: 'min' },
  { id: 'px51', name: 'クランチ',                muscle: 'core',      unit: 'bw' },
  { id: 'px52', name: 'レッグレイズ',            muscle: 'core',      unit: 'bw' },
  { id: 'px53', name: 'アブローラー',            muscle: 'core',      unit: 'bw' },
  { id: 'px54', name: 'サイドプランク',          muscle: 'core',      unit: 'min' },
  { id: 'px60', name: 'ランニング',              muscle: 'cardio',    unit: 'min' },
  { id: 'px61', name: 'ウォーキング',            muscle: 'cardio',    unit: 'min' },
  { id: 'px62', name: 'エアロバイク',            muscle: 'cardio',    unit: 'min' },
  { id: 'px63', name: '水泳',                    muscle: 'cardio',    unit: 'min' },
  { id: 'px64', name: '縄跳び',                  muscle: 'cardio',    unit: 'min' },
  /* ▼ 通っているジムのマシン（ホリデイ草津・LifeFit広島駅北） */
  { id: 'px70', name: 'ペックフライ',              muscle: 'chest',     unit: 'kg' },
  { id: 'px71', name: 'デルツマシン（リアデルト）', muscle: 'shoulders', unit: 'kg' },
  { id: 'px72', name: 'マシンアームカール',        muscle: 'arms',      unit: 'kg' },
  { id: 'px73', name: 'アームエクステンション',    muscle: 'arms',      unit: 'kg' },
  { id: 'px74', name: 'アブドミナルクランチ',      muscle: 'core',      unit: 'kg' },
  { id: 'px75', name: 'ロータリートーソ',          muscle: 'core',      unit: 'kg' },
  { id: 'px76', name: 'トータルアブドミナル',      muscle: 'core',      unit: 'kg' },
  { id: 'px77', name: 'ヴァーティカルトラクション', muscle: 'back',     unit: 'kg' },
  { id: 'px78', name: 'アッパーバック',            muscle: 'back',      unit: 'kg' },
  { id: 'px79', name: 'ローワーバック',            muscle: 'back',      unit: 'kg' },
  { id: 'px80', name: 'マルチヒップ',              muscle: 'legs',      unit: 'kg' },
  { id: 'px81', name: 'アブダクター（外もも）',    muscle: 'legs',      unit: 'kg' },
  { id: 'px82', name: 'アダクター（内もも）',      muscle: 'legs',      unit: 'kg' },
  { id: 'px83', name: 'グルートマシン',            muscle: 'legs',      unit: 'kg' },
  { id: 'px84', name: 'ロータリーカーフ',          muscle: 'legs',      unit: 'kg' },
  { id: 'px85', name: 'スミスマシンスクワット',    muscle: 'legs',      unit: 'kg' },
  { id: 'px87', name: 'クロストレーナー',          muscle: 'cardio',    unit: 'min' },
  { id: 'px88', name: 'リクラインバイク',          muscle: 'cardio',    unit: 'min' },
  { id: 'px89', name: 'ステップマシン',            muscle: 'cardio',    unit: 'min' },
];

/* よく食べるもの（1人前のめやす。保存前に編集可能） */
const QUICK_FOODS = [
  { name: '白ご飯 茶碗1杯(150g)', kcal: 234, p: 3.8,  f: 0.5,  c: 53 },
  { name: 'おにぎり1個',           kcal: 180, p: 4,    f: 1,    c: 38 },
  { name: '食パン6枚切1枚',        kcal: 156, p: 5.6,  f: 2.6,  c: 28 },
  { name: 'パスタ1人前',           kcal: 600, p: 20,   f: 18,   c: 85 },
  { name: 'ラーメン1杯',           kcal: 550, p: 18,   f: 17,   c: 75 },
  { name: 'カレーライス',          kcal: 750, p: 15,   f: 25,   c: 110 },
  { name: '牛丼 並盛',             kcal: 635, p: 20,   f: 20,   c: 92 },
  { name: '鶏むね肉(皮なし100g)',  kcal: 105, p: 23,   f: 1.5,  c: 0 },
  { name: 'サラダチキン1個',       kcal: 115, p: 24,   f: 1.5,  c: 1 },
  { name: '鶏もも肉(100g)',        kcal: 190, p: 17,   f: 13,   c: 0 },
  { name: '豚ロース(100g)',        kcal: 248, p: 19,   f: 19,   c: 0 },
  { name: '牛赤身肉(100g)',        kcal: 193, p: 21,   f: 11,   c: 0.5 },
  { name: '鮭1切れ',               kcal: 140, p: 18,   f: 7,    c: 0.1 },
  { name: 'サバ味噌煮缶1缶',       kcal: 340, p: 26,   f: 25,   c: 2 },
  { name: '卵1個',                 kcal: 76,  p: 6.2,  f: 5.2,  c: 0.2 },
  { name: '納豆1パック',           kcal: 95,  p: 8,    f: 5,    c: 6 },
  { name: '豆腐 半丁(150g)',       kcal: 110, p: 10,   f: 6,    c: 3 },
  { name: 'プロテイン1杯',         kcal: 120, p: 24,   f: 1.5,  c: 3 },
  { name: '牛乳コップ1杯(200ml)',  kcal: 126, p: 6.6,  f: 7.6,  c: 9.6 },
  { name: 'ヨーグルト(100g)',      kcal: 62,  p: 3.6,  f: 3,    c: 4.9 },
  { name: 'バナナ1本',             kcal: 93,  p: 1.1,  f: 0.2,  c: 22.5 },
  { name: 'サラダ小鉢',            kcal: 25,  p: 1,    f: 0.2,  c: 5 },
  { name: '味噌汁1杯',             kcal: 40,  p: 3,    f: 1,    c: 5 },
  { name: 'ビール500ml',           kcal: 200, p: 2,    f: 0,    c: 16 },
];

/* タンパク質を補う食品（提案用） */
const PROTEIN_FIXES = [
  { name: 'プロテイン1杯',       p: 24, kcal: 120 },
  { name: 'サラダチキン1個',     p: 24, kcal: 115 },
  { name: '鶏むね肉100g',        p: 23, kcal: 105 },
  { name: 'ゆで卵2個',           p: 12, kcal: 152 },
  { name: '納豆1パック',         p: 8,  kcal: 95 },
  { name: 'ギリシャヨーグルト',  p: 10, kcal: 69 },
  { name: 'サバ缶1缶',           p: 26, kcal: 340 },
  { name: '豆腐半丁',            p: 10, kcal: 110 },
];
